networks:
  default:
    driver: bridge
  database-network:
    driver: bridge
    name: database-network

include:
  # PREFIX prod = Production Docker Server
  # Deploy: docker compose -f /home/goug76/docker/docker-compose-prod.yml up -d
  # Remove: docker compose -f /home/goug76/docker/docker-compose-prod.yml down
  # Logs: docker compose -f /home/goug76/docker/docker-compose-prod.yml logs <container name>

  # CORE
  - compose/portainer-agent.yml

  # Monitoring
  - compose/glances.yml

  # Database
  - compose/postgres.yml

  # Single Sign On
  - compose/prod/authentik.yml

  # Dashboard
  - compose/prod/dashy.yml