services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    restart: unless-stopped
    ports:
      - 80:8080
    environment:
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/dashy/conf.yml:/app/user-data/conf.yml
      - $DOCKERDIR/dashy/icons:/app/public/item-icons/icons
    networks:
      - default